import { Separator } from "@/components/ui/separator";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function costumerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-[#232323] flex flex-col items-center">
      <div className="bg-[#18181B] w-[1440px] h-[68px] px-22 flex items-center justify-between">
        <div className="flex gap-x-4 items-center">
          <img
            src="Screenshot 2024-12-17 at 18.02.18 1 (Traced).png"
            alt=""
            className="h-[37px]"
          />
          <div>
            <div className="flex font-semibold text-[20px] text-white">
              Nom<p className="text-[#EF4444]">Nom</p>
            </div>
            <div className="text-white">Swift delivery</div>
          </div>
        </div>
        <div className="flex gap-[14px]">
          <div className="flex gap-1 px-4 h-9 bg-white items-center rounded-3xl">
            <img src="Location Icon.png" alt="" />
            <p className="text-[#EF4444]">Delivery address:</p>
            <p className="text-[#71717A]">Add Location</p>
            <img src="Chevron Icon.png" alt="" />
          </div>
          <div className="w-9 h-9 bg-white rounded-[100px] flex justify-center items-center">
            <img src="shopping-cart.png" alt="" />
          </div>
          <div className="w-9 h-9 bg-[#EF4444] rounded-[100px] flex justify-center items-center">
            <img src="user.png" alt="" />
          </div>
          <div></div>
        </div>
      </div>
      {children}
      <div className="w-[1440px] overflow-x-hidden bg-[#18181B]">
        <div className="py-7 w-fit bg-[#EF4444]  h-[92px] mt-15 text-white text-[30px] font-semibold  pl-[98px] gap-[34px] flex ">
          <div className="w-[272px]">Fresh fast delivered </div>
          <div className="w-[272px]">Fresh fast delivered </div>
          <div className="w-[272px]">Fresh fast delivered </div>
          <div className="w-[272px]">Fresh fast delivered </div>
          <div className="w-[272px]">Fresh fast delivered </div>
        </div>
        <div className=" relative mt-[76px] flex flex-col px-22">
          <div className="w-22 flex flex-col justify-center items-center gap-4">
            <img src="footlogo.png" alt="" className="w-[46px]" />
            <div className="flex flex-col text-white">
              <div className="flex text-[20px] font-semibold">
                <h1 className="text-[#EF4444]">Nom</h1>Nom
              </div>
              <div className="text-[12px]">Swift delivery</div>
            </div>
          </div>
          <div className="h-fit flex justify-between absolute left-[308px] w-[768px] text-white">
            <div className="flex flex-col gap-4">
              <h1 className="text-[#71717A]">NOMNOM</h1>
              <p>Home</p>
              <p>Contact us</p>
              <p>Delivery zone</p>
            </div>
            <div className="flex gap-14">
              <div className="w-[132px] flex flex-col gap-4">
                <h1 className="text-[#71717A]">MENU</h1>
                <p>Appetizers</p>
                <p>Salads</p>
                <p>Pizzas</p>
                <p>Main dishes</p>
                <p>Desserts</p>
              </div>
              <div className="w-[132px] flex flex-col gap-4">
                <h1 className="text-transparent">N</h1>
                <p>Side dish </p>
                <p>Brunch</p>
                <p>Desserts</p>
                <p>Beverages</p>
                <p>Fish & Sea foods</p>
              </div>
            </div>
            <div className="flex flex-col gap-4">
              <h1 className="text-[#71717A]">FOLLOW US</h1>
              <div className="flex gap-4">
                <img src="fb.png" alt="" />
                <img src="insta.png" alt="" />
              </div>
            </div>
          </div>
          <Separator className="bg-[#71717A] mb-8 mt-[236px]"></Separator>
          <div className="mb-[85px] flex gap-12 text-[#71717A]">
            <div className="flex gap-1">
              Copy right 2024 <div>©</div>
              Nomnom LLC
            </div>
            <div>Privacy policy </div>
            <div>Terms and conditoin</div>
            <div>Cookie policy</div>
          </div>
        </div>
      </div>
    </div>
  );
}
