export const Data = [
  {
    id: "Coffee",
    name: "iced ammericano",
    imageUrl: "americano.png",
    featured: "no",
    past: "yes",
    favourite: true,
  },
  {
    id: "Coffee",
    name: "iced latte",
    imageUrl: "latte.png",
    featured: "no",
    favourite: true,
  },
  {
    id: "Coffee",
    name: "iced macchiato",
    imageUrl: "macchiato.png",
    featured: "no",
    past: "yes",
    favourite: false,
  },
  {
    id: "Coffee",
    name: "iced mocha",
    imageUrl: "mocha.png",
    featured: "yes",
    past: "no",
    favourite: false,
  },
  {
    id: "Coffee",
    name: "esperesso",
    imageUrl: "esperesso.png",
    featured: "no",
    past: "no",
    favourite: false,
  },
  {
    id: "Coffee",
    name: "affogato",
    imageUrl: "affogato.png",
    featured: "yes",
    past: "no",
    favourite: true,
  },
  {
    id: "Tea",
    name: "iced green tea",
    imageUrl: "green.png",
    featured: "no",
    past: "no",
    favourite: false,
  },
  {
    id: "Tea",
    name: "iced lemonade",
    imageUrl: "lemonade.png",
    featured: "no",
    past: "no",
    favourite: false,
  },
  {
    id: "Tea",
    name: "iced lime tea",
    imageUrl: "lime.png",
    featured: "no",
    past: "no",
    favourite: true,
  },
  {
    id: "Tea",
    name: "iced grapefruit Tea",
    imageUrl: "grapefruit.png",
    featured: "yes",
    past: "no",
    favourite: false,
  },
  {
    id: "Tea",
    name: "iced tea",
    imageUrl: "iced tea.png",
    featured: "no",
    past: "no",
    favourite: false,
  },
  {
    id: "Smoothie",
    name: "plain yogurt smoothie",
    imageUrl: "plain.png",
    featured: "no",
    past: "no",
    favourite: true,
  },
  {
    id: "Smoothie",
    name: "orei smoothie",
    imageUrl: "oreo.png",
    featured: "no",
    past: "no",
    favourite: true,
  },
  {
    id: "Smoothie",
    name: "green tea smoothie",
    imageUrl: "greens.png",
    featured: "yes",
    past: "no",
    favourite: false,
  },
];
